# Generated by Django 4.0.3 on 2022-04-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_supporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='closing_date',
            field=models.DateField(),
        ),
    ]
